services:
  backend:
    build: ./backend
    image: shawnyu5/gh_actions_dashboard_backend
    ports:
      - "8001:8001"
    env_file:
      - ./backend/.env
    hostname: backend
    restart: always

  frontend:
    build: ./frontend
    image: shawnyu5/gh_actions_dashboard_frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    restart: always
